name: DockerHub

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_PATH: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
      GHCR_IMAGE_PATH: ghcr.io/${{ github.repository }}
      IMAGE_VERSION_PREFIX: ''
      CADDY_VERSION: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_BUILD_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker images (multi-platform)
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: |
            linux/amd64,
            linux/arm64
          build-args: |
            CADDY_VERSION=${{ env.CADDY_VERSION }}
          tags: |
            ${{ env.DOCKER_IMAGE_PATH }}:${{ env.IMAGE_VERSION_PREFIX }}${{ env.CADDY_VERSION }},
            ${{ env.GHCR_IMAGE_PATH }}:${{ env.IMAGE_VERSION_PREFIX }}${{ env.CADDY_VERSION }}

