name: DockerHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_PATH: nstwf/caddy
      CADDY_VERSION: 2

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        run: echo ${{ secrets.DOCKER_BUILD_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker images
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_PATH }}:${{ env.CADDY_VERSION }} --build-arg CADDY_VERSION=${{ env.CADDY_VERSION }} .
          docker push ${{ env.DOCKER_IMAGE_PATH }}:${{ env.CADDY_VERSION }}
