name: Build and Push Using Shared Workflow

permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 4 * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-push:
    if: github.event_name != 'pull_request'

    permissions:
      contents: read

    strategy:
      matrix:
        version:
          - '2'

    uses: nstwf-d/docker-ci/.github/workflows/docker-build-push.yaml@main
    secrets: inherit
    with:
      image_version: ${{ matrix.version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
      docker_extra_build_args: |
        CADDY_VERSIJON=${{ matrix.version }}
      platforms: |
        linux/amd64
        linux/arm64
      ghcr_image: ghcr.io/${{ github.repository }}
