name: Build and Push Using Shared Workflow

permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    permissions:
      contents: read
  build-push:
    if: github.event_name != 'pull_request'

    strategy:
      matrix:
        version:
          - '2'

    uses: nstwf-docker/docker-ci/.github/workflows/docker-build-push.yaml@main
    secrets: inherit
    with:
      image_version: ${{ matrix.version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
      docker_extra_build_args: |
        CADDY_VERSIJON=${{ matrix.version }}
      ghcr_image: ghcr.io/${{ github.repository }}

    permissions:
      contents: read
      pull-requests: write
  build-push-pr:
    if: github.event_name == 'pull_request'

    strategy:
      matrix:
        version:
          - '2'

    uses: nstwf-docker/docker-ci/.github/workflows/docker-build-push-pr.yaml@main
    secrets: inherit
    with:
      image_version: ${{ matrix.version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
      docker_extra_build_args: |
        CADDY_VERSIJON=${{ matrix.version }}